{
 "title": "Kafka Data",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# SPO System\n\nDiagnostics for SPO System"
   }
  },
  {
   "title": "CPU Usage (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=\"kafka\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic (frame_noticifation)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_noticifation\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic (frame_noticifation)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_noticifation\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Speed of Neural Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nn_detections_total[1m]))",
     "legendFormat": "Frames"
    }
   ]
  }
 ]
}