{
 "title": "Kafka Data",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# SPO System\n\nDiagnostics for SPO System"
   }
  },
  {
   "title": "CPU Usage (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=\"kafka\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (Kafka)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_notification\"}[1m]))",
     "legendFormat": "frame_notification"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_detection\"}[1m]))",
     "legendFormat": "frame_detection"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_notification\"}[1m]))",
     "legendFormat": "frame_notification"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_detection\"}[1m]))",
     "legendFormat": "frame_detection"
    }
   ]
  },
  {
   "title": "Speed of Neural Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(rate(nn_frames_total[1m]))", "legendFormat": "Frames" }
   ]
  },
  {
   "title": "Skipped Frames",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Vehicles per frame",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Detection time per frame",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "nn_detection_time", "legendFormat": "__auto" }
   ]
  }
 ]
}