{
 "title": "Kafka Data",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_notification\"}[1m]))",
     "legendFormat": "frame_notification"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"frame_detection\"}[1m]))",
     "legendFormat": "frame_detection"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(process_cpu_seconds_total{job=\"kafka\"}[1m])) * 100",
     "legendFormat": "kafka"
    },
    { "expr": "nn_cpu_usage", "legendFormat": "detection" }
   ]
  },
  {
   "title": "Speed of Neural Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(rate(nn_frames_total[1m]))", "legendFormat": "Frames" }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_notification\"}[1m]))",
     "legendFormat": "frame_notification"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"frame_detection\"}[1m]))",
     "legendFormat": "frame_detection"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"kafka\"})",
     "legendFormat": "kafka"
    },
    { "expr": "nn_memory_usage", "legendFormat": "detection" }
   ]
  },
  {
   "title": "Detection time per frame",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nn_detection_time", "legendFormat": "detection" },
    { "expr": "nn_total_frame_time", "legendFormat": "total" }
   ]
  },
  {
   "title": "Vehicles per frame",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(nn_vehicles_ignored_total[1m])",
     "legendFormat": "vehicle_ign"
    },
    {
     "expr": "rate(nn_vehicles_left_total[1m])",
     "legendFormat": "vehicle_l"
    },
    {
     "expr": "rate(nn_vehicles_right_total[1m])",
     "legendFormat": "vehicle_r"
    },
    {
     "expr": "rate(nn_vehicles_straight_total[1m])",
     "legendFormat": "vehicle_s"
    },
    { "expression": "($A + $B + $C + $D)", "type": "math" }
   ]
  }
 ]
}